# Generated by Django 3.2.18 on 2023-06-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_auto_20230530_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'married'), ('inlove', 'In Love')], default='single', max_length=100, null=True),
        ),
    ]
