# Generated by Django 3.2.18 on 2023-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_page_options'),
        ('userauths', '0005_profile_friends_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='pages', to='core.Page'),
        ),
    ]
