# Generated by Django 3.2.18 on 2023-06-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
