# Generated by Django 3.2.18 on 2023-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230614_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
