# Generated by Django 4.0.1 on 2024-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230722_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomVideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=200)),
                ('insession', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_paths',
            field=models.CharField(default='', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_paths',
            field=models.CharField(default='', max_length=10000000000),
        ),
    ]
