# Generated by Django 4.0.1 on 2024-04-20 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_roomvideocall_chatmessage_file_paths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='memebers',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
