# Generated by Django 4.0.1 on 2024-04-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_group_memebers_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
