# Generated by Django 4.0.1 on 2024-04-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_group_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='topic',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
