# Generated by Django 4.0.1 on 2024-05-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_group_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
